### ISSUE TITLE
The CS:Go Tracker Desktop Application does not sanitize URLs going to `shell.openExternal()`

### ISSUE THREAD

**Issue by masood** [davidaf3/csgo-tracker#4]
### Summary:

The CS:Go Tracker Desktop Application does not correctly restrict navigation. While it does pass attempts to open new window to the system’s default browser, it does not sanitize these URLs, resulting in the execution of sensitive files on the user’s system.

### Platform(s) Affected:

Linux, Window

### Steps To Reproduce:

1. Open the CS:Go Tracker Desktop Desktop Application from the command-line. Add a command-line switch `--remote-debugging-port=8315` while running the application.

2. Open a web browser on the same device and visit `localhost:8315`. The application can be interacted with via the DevTools protocol.

3. [Access Sensitive File] Within the console, update the location, say, `window.open = “file:///path/to/file”. The file at the given path is opened. If this file is an executable, it is run by the system.

4. [In-app Navigation] The app also does not have an event handler on `will-navigate`. Updating the app’s window location by using `window.location=”https://malicious.com/”` with navigate the app’s window away to an external site.

Mir Masood Ali, PhD student, University of Illinois at Chicago
Mohammad Ghasemisharif, PhD Candidate, University of Illinois at Chicago
Chris Kanich, Associate Professor, University of Illinois at Chicago
Jason Polakis, Associate Professor, University of Illinois at Chicago

**Comment by davidaf3** [comment]
Thanks for reporting, but I don't think this is a problem because csgo-tracker is an offline app. To exploit this vulnerability an attacker would need access to your computer. In that case I think there would be bigger concerns than navigating to a malicious website. Just in case I have added a check in https://github.com/davidaf3/csgo-tracker/commit/dc14f6ed7ca7297ab4fd7896007eed04071fcb42 to only allow opening HTTPS URLs.
